import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Troscan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}
